name = input("What is your name? ")
print("Hi "+ str(name))
birth_year = input("Enter your birth year : ")
print("the birth year you entered is : ", birth_year)
age =  2023 - int(birth_year)
print(str(name) + "," + " your Age is : " , int(age))
